CREATE OR REPLACE FUNCTION validateBirthDate()
RETURNS TRIGGER AS $$
BEGIN
  IF(NEW.BirthDate < '1900-01-01' OR NEW.BirthDate > CURRENT_DATE) THEN
    RAISE EXCEPTION 'Invalid birth date.';
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER validateBirthDate
BEFORE INSERT OR UPDATE ON Users
FOR EACH ROW EXECUTE PROCEDURE validateBirthDate();

